<?php
$room_data_array = array(
    '1:13:3:0' => array(
        'width' => 0,
        'height' => 0,
        'type' => 'room',
        'name' => 'all',
        'index' => '0',
    ),
    '1:7:1:1' => array(
        'width' => 15,
        'height' => 4,
        'type' => 'room',
        'name' => '青島東',
        'index' => '1',
    ),
    '1:7:7:1' => array(
        'width' => 15,
        'height' => 4,
        'type' => 'room',
        'name' => '立法院',
        'index' => '2',
    ),
    '1:7:13:1' => array(
        'width' => 15,
        'height' => 4,
        'type' => 'room',
        'name' => '濟南',
        'index' => '3',
    ),
);
